export const pahtToProductKey = {
  confeti: "confeti",
  daruda: "daruda",
  코코스: "cocos",
  휘피: "whipee",
  절로가: "jeolloga",
  Dash: "dash",
  공백: "gongbaek",
  Roomie: "roomie",
  acon: "acon",
  제_과제_빵점: "bbangjeom",
  Spoony: "spoony",
  Memento: "memento",
  수현이랑: "suhyun",
  납작마켓: "napzak",
  Shellin: "shellin",
  SOPT_makers: "makers",
};
